### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#165]
We should have a optional dark mode for the Alva application, so users can work better in Dark environments or have an better contrast if they are working on a light website.

**Comment by agustif** [comment]
I would like to help both with these and the settings, would this make a good first-issue PR candidate? is anyone already working on this?

**Comment by agustif** [comment]
We can detect if DarkMode is enabled in MacOS System Preferences: https://github.com/electron/electron/blob/master/docs/api/system-preferences.md

**Comment by LKuechler** [comment]
@agustif Thanks for your support. We really appreciate that.
As far as i know no one startet work on this issue.
Just make sure that you don't try to do to much stuff at once and then it should be a good first-issue.

But if you find some part that is hard to understand, feel free to ask. :)

**Comment by agustif** [comment]
Sure, so where you would start, making a -preferences- setting available or starting tweaking on the dark mode (and caring later how to enable/disable it, first issue can be related to system preferences instead of being an app preference, DRY I guess

**Comment by LKuechler** [comment]
I would have probably started with adding a dark mode to the components but both ways have there benefits.

**Comment by tilmx** [comment]
Hey @agustif! Thanks a lot for contributing! 🚀 
I just created a rough design for a dark mode and attached it as a PNG here. I hope it helps a bit.
![alva darkmode](https://user-images.githubusercontent.com/8946766/34344287-9f83e904-e9e4-11e7-964b-5db0a368b7f3.png)

**Comment by agustif** [comment]
@tilmx Looks awesome, I just forked it and am trying to get a feel of electron, I only know React+NextJS+Apollo for webDev.

I've hacked editing some file sin lsg/patterns, it needs polish 
<img width="1289" alt="screenshot 2017-12-26 03 29 01" src="https://user-images.githubusercontent.com/6601142/34345251-caeba42a-e9ed-11e7-9aa2-923af3afece5.png">

<img width="524" alt="screenshot 2017-12-26 03 35 33" src="https://user-images.githubusercontent.com/6601142/34345260-d84a4e46-e9ed-11e7-90b7-d1a352d8b826.png">

**Comment by tilmx** [comment]
@agustif Looks really cool already! Thank you so much. If you need anything, let us know! 🚀

**Comment by agustif** [comment]
Thanks for the kind words @tilmx , awesome that you open-sourced this from the beginning, I've been reluctant to pay for Sketch/Photoshop because I only use them sporadically, and have been coding more and designing less, BUT this is awesome and can be a great hybrid between Storybook + Sketch, so you can prototype/design based on real react components, which is awesome!

Anyway, about going dark.

for a v1 instead of creating the settings panel, we could just read system.preferences dark setting and go with that, we can add a enable/disable dark mode button later, or link it maybe to night shift instead of dark mode, I have dark mode ON all time, I like the transparent black menubar on OSX, but I only enable night shift when working at night, which could be a good use case of using light theme during the day, and dark theme during the night.

Anyway, how would you approach this, should we put logic in the colors file, something kinda like, if system.preferences.dark enabled, invert color palette.

Or where do we put the logic?

**Comment by LKuechler** [comment]
hi @agustif. Thanks again for contributing :)
I would have tried to add it in the colors file and just switch the colors in there based on the setting or night mode.

Maybe create new variables with the switch between the two colors.

**Comment by agustif** [comment]
I will try that and open a PR if I succeed, my current approach changed too many files, which is not optim for enabling a true dark/light feature but just a quick hack for dark mode

**Comment by Jumace** [comment]
Hey @agustif,
if need any help with that feature, feel free to start a discussion here or write me personally :)

**Comment by agustif** [comment]
Hi a lot of work for my employer lately, I will take a look again doing it from start since the code must have evolved a bit since I tried a stab at it! If I hit any walls I will report back here with my progress.

@Jumace Thx for the encouragement

**Comment by Jumace** [comment]
Hey @agustif,

no problem, this is a open source project so we know most people work on their free time on the project and free time is limited ;)

I'm really looking forward to use a dark theme in the future :D

And as always feel free to reach out to LKuechler, tilmx or me if you have questions or need support.

**Comment by agustif** [comment]
Hi Julian @Jumace , I would love to retake this in order to improve my github hierability,

please let me know how you would approach it as a feature in the roadmap, since all I did was just to tweak some stuff, but we would need to make this inteligently so you can enable/disable dark at will  as an end user

**Comment by Jumace** [comment]
Hey Agusti @agustif, nice to hear from you again :)

I've spoke with @LKuechler and @markusoelhafen about that issue again and you're right. A user should be able to switch between themes.

We created a [new issue](https://github.com/meetalva/alva/issues/343) which covers this.
There is also [a PR](https://github.com/meetalva/alva/pull/342) to this issue because we wanted to prepare the usage of themes a bit.
We prepared it a bit but there is still work to do in the PR.
I suggest that you have a look at the new PR and issue, if it looks suitable for you give it a try.

Please note us if you start to work on it, so nobody from us will start with it.

And don't forget we are always there to support if needed ;)

**Comment by yuzl** [comment]
ot of scope - may be reopened later
