### ISSUE TITLE
Support Vue.js Libraries

### ISSUE THREAD

**Issue by tilmx** [meetalva/alva#382]
Alva should support not only React.js libraries, but also Vue.js libraries. We have to evaluate what has to be done for that.

There already was a Open Source Hackathon planned, but moved into the future due to illness.

**Comment by OldrichKruchna** [comment]
What is the status of the Hackathon? I would be interested in case you would organize it :)

**Comment by escapedcat** [comment]
Same here. Only waiting for a date (again).

**Comment by jancborchardt** [comment]
@yuzl was this removed from the roadmap? Just asking cause I can’t see any reference to Vue.js in recent commits or pull requests which could suggest it was implemented. Statement on this would be cool – thanks for the great work! :heart:

**Comment by yuzl** [comment]
Dear Jan @jancborchardt, 

Vue.js ist not at all entirely removed from our roadmap. We would very much like to support more libraries such as Vue.js in the mid-term future.

While the last month were kind of silent around feature production, we are currently putting all our efforts into coming back on track bigger and better than ever before.

Since there is no actual timing on vue.js and other issues, we decided to clean up a little bit, until we have a clearer picture and the resources needed for proper execution.

We have some exciting month ahead of us!

Cheers,
Yuri
