### ISSUE TITLE
Improvements for the iframe-client/server refactoring

### ISSUE THREAD

**Issue by TheReincarnator** [meetalva/alva#408]
@marionebl did the fantastic job to change the preview webview (renderer) to an iframe, introducing a server and webpack.
The change was big and we all wanted to get the long-running PR into the master.
I'd now like to discuss some minor style, documentation, and code partitioning topics that could be done on top of this change.

The list is incomplete, it would be nice if someone reviewed the commit 2e44d27786 again and complete the list.

- I think that the `src/electron` folder is overloaded now with non-electron stuff. We should move all new preview stuff, including the server, into a folder named `preview`.
- Many files do not have a documentation (JSDoc).
- Some files are not sorted at all, like the server.ts. Exported and not exported mix, and types and functions mix. I think we should write down a coding guide for that, as it help (at least me) to orientate.
- Rename `message/index.ts` to `message.ts` (we usually do that)
- Maybe even relocate message.ts to a different folder to bind it to its use?

**Comment by marionebl** [comment]
> - I think that the `src/electron` folder is overloaded now with non-electron stuff. We should move all new preview stuff, including the server, into a folder named `preview`.

Yep, let's do that

> - Many files do not have a documentation (JSDoc).

Sure, but we should prioritize what type of docs is most important at the moment. Being freshly onboarded on developing in Alva I'd like to suggest we invest into high-level docs describing the general architecture, processes etc before doing low-level method descriptions. 

> - Some files are not sorted at all, like the server.ts. Exported and not exported mix, and types and functions mix. I think we should write down a coding guide for that, as it help (at least me) to orientate.

Sure, I am fine with sorted/unsorted, mixed/separate as long as we do not introduce classes just for the sake of moving things around.

> - Rename `message/index.ts` to `message.ts` (we usually do that)

If that is the case I'd vote for changing to `message/index` instead of `message/message`. There is special support for `index` files in the Node.js resolve algorithm and to it appears like the conventional choice in the ecosystem.

> - Maybe even relocate message.ts to a different folder to bind it to its use?

Conceptually `Message` will remain in the odd "spans all" position required by all processes in the application. I'd suggest we keep it on that shared position (while moving everything else into folders that mark something as being in the `main`, `renderer` or `iframe` context)

**Comment by marionebl** [comment]
Closing as we moved from the code base as it has been then and most concerns have been adressed.
