### ISSUE TITLE
Don't check for update if there is no internet

### ISSUE THREAD

**Issue by LKuechler** [meetalva/alva#525]
**Describe the bug**
Without internet Alva still try's to check for updates.
This causes two error messages.

**To Reproduce**
1. Don't have a internet connection
2. Start Alva

**Expected behavior**
If there is no internet Alva should not check for updates.

**Comment by barinali** [comment]
Checking internet connection should be done in the renderer process. But auto updater's flow happens in the main one. So instead of communicating between the processes, we may just remove one of the error dialogs and keep the flow same.

Since we don't have a page for updates and show dialogs for updates, I guess this approach is fine.

**Comment by marionebl** [comment]
Fixed by ignoring errors if both of the following conditions are met:

* An update check was triggered automatically
* The exception thrown has message `net::ERR_INTERNET_DISCONNECTED`

See: https://github.com/meetalva/alva/commit/02002711a0cf74b9204e9fe377accd78cd9eaab1
